In [3]:
import random
print("this is a random number: %3d" % random.randint(1,101))

this is a random number:  57


In [2]:
import numpy as np
a = np.array(np.arange(6)).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [4]:
b = np.array(np.arange(8)).reshape(-1,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]
