In [9]:
import random
print("this is a random number: %3d" % random.randint(1,101))

this is a random number:  69


In [10]:
import numpy as np
a = np.array(np.arange(6)).reshape(2,3)
print(a)

[[0 1 2]
 [3 4 5]]


In [11]:
b = np.array(np.arange(8)).reshape(-1,4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [12]:
c = b.T.dot(a)
print(c)

[[12 16 20]
 [15 21 27]
 [18 26 34]
 [21 31 41]]


In [13]:
d = a.T.dot(b)
print d